export const formatDate = (dateString) => {
  const date = new Date(dateString);
  const options = { year: 'numeric', month: 'long', day: 'numeric' };
  return date.toLocaleDateString('en-US', options);
};

export const getYear = (dateString) => {
  const date = new Date(dateString);
  const options = { year: 'numeric' };
  return date.toLocaleDateString('en-US', options);
}

export const formatMoney = (budget) => {
  const abs = Math.abs(Number(budget));
  return '$' + (
    abs >= 1.0e+9
      ? (abs / 1.0e+9).toFixed(1) + 'B'
      : abs >= 1.0e+6
        ? (abs / 1.0e+6).toFixed(1) + 'M'
        : abs >= 1.0e+3
          ? (abs / 1.0e+3).toFixed(1) + 'K'
          : abs
  );
};

export const genres = [
  'Action', 
  'Adventure', 
  'Animation', 
  'Comedy', 
  'Crime', 
  'Documentary', 
  'Drama', 
  'Family', 
  'Fantasy', 
  'History', 
  'Horror', 
  'Music', 
  'Mystery', 
  'Romance', 
  'Science Fiction', 
  'Thriller', 
  'TV Movie', 
  'War', 
  'Western'
];

export const providers = [
  'A&E Crime Central Apple TV Channel',
  'Acorn TV', 
  'Acorn TV Apple TV', 
  'AcornTV Amazon Channel', 
  'AD tv', 
  'aha', 
  'ALLBLK Apple TV channel', 
  'Amazon Prime Video', 
  'Amazon Video', 
  'AMC', 
  'AMC on Demand', 
  'AMC Plus Apple TV Channel ', 
  'AMC+', 
  'AMC+ Amazon Channel', 
  'AMC+ Roku Premium Channel', 
  'Angel Studios', 
  'Apple TV', 
  'Apple TV Plus', 
  'ARROW', 
  'AsianCrush', 
  'BBC America', 
  'Bet+', 
  'BET+  Apple TV channel', 
  'Bet+ Amazon Channel', 
  'Boomerang', 
  'Boomerang Amazon Channel', 
  'BritBox', 
  'BritBox Amazon Channel', 
  'Britbox Apple TV Channel ', 
  'BroadwayHD', 
  'Carnegie Hall+ Amazon Channel', 
  'Carnegie Hall+ Apple TV Channel', 
  'Chai Flicks', 
  'Cinemax Amazon Channel', 
  'Cinemax Apple TV Channel', 
  'Cineverse', 
  'Classix', 
  'Cohen Media Amazon Channel', 
  'Comedy Central', 
  'Crackle', 
  'Criterion Channel', 
  'Crunchyroll', 
  'Crunchyroll Amazon Channel', 
  'Cultpix', 
  'Curiosity Stream', 
  'CuriosityStream Apple TV Channel', 
  'Darkmatter TV', 
  'Dekkoo', 
  'DIRECTV', 
  'Discovery+ Amazon Channel', 
  'Disney Plus', 
  'DisneyNOW', 
  'DistroTV', 
  'DocAlliance Films', 
  'DOCSVILLE', 
  'Dogwoof On Demand', 
  'Eros Now', 
  'Eros Now Select Apple TV Channel', 
  'Eventive', 
  'Fandor', 
  'Fandor Amazon Channel', 
  'Film Movement Plus', 
  'FilmBox+', 
  'FILMRISE', 
  'Filmzie', 
  'Flix Premiere', 
  'FlixFling', 
  'Freeform', 
  'Freevee', 
  'fuboTV', 
  'Full Moon Amazon Channel', 
  'Funimation Now', 
  'FXNow', 
  'GlewedTV', 
  'Google Play Movies', 
  'GuideDoc', 
  'Hallmark Movies Now Amazon Channel', 
  'Hallmark Movies Now Apple TV Channel', 
  'HBO Max', 
  'Here TV', 
  'Hi-YAH', 
  'HiDive', 
  'History', 
  'History Vault', 
  'HISTORY Vault Amazon Channel', 
  'HISTORY Vault Apple TV Channel', 
  'Hoichoi', 
  'Hoopla', 
  'Hulu', 
  'IFC Films Unlimited Apple TV Channel', 
  'IndieFlix', 
  'iQIYI', 
  'Kanopy', 
  'Kino Now', 
  'Klassiki', 
  'Kocowa', 
  'KoreaOnDemand', 
  'Laugh Out Loud', 
  'Lifetime', 
  'Lifetime Movie Club', 
  'Lifetime Movie Club Amazon Channel', 
  'Lifetime Movie Club Apple TV Channel', 
  'Magellan TV', 
  'Max', 
  'Max Amazon Channel', 
  'Metrograph', 
  'MGM Plus', 
  'MGM Plus Amazon Channel', 
  'MGM Plus Roku Premium Channel', 
  'Microsoft Store', 
  'Midnight Pulp', 
  'MovieSaints', 
  'MUBI', 
  'MUBI Amazon Channel', 
  'myfilmfriend', 
  'MZ Choice Amazon Channel', 
  'National Geographic', 
  'Netflix', 
  'Netflix basic with Ads', 
  'Netflix Kids', 
  'Night Flight Plus', 
  'Noggin Amazon Channel', 
  'Noggin Apple TV Channel', 
  'Outside Watch', 
  'OUTtv Apple TV Channel', 
  'OVID', 
  'Pantaflix', 
  'Paramount Plus', 
  'Paramount Plus Apple TV Channel ', 
  'Paramount+ Amazon Channel', 
  'Paramount+ Roku Premium Channel', 
  'Paramount+ with Showtime', 
  'PBS', 
  'PBS Kids Amazon Channel', 
  'PBS Masterpiece Amazon Channel', 
  'Peacock', 
  'Peacock Premium', 
  'Plex', 
  'Plex Player', 
  'Pluto TV', 
  'Popcornflix', 
  'Popflick', 
  'Public Domain Movies', 
  'Pure Flix', 
  'Rakuten Viki', 
  'Redbox', 
  'Retrocrush', 
  'Reveel', 
  'Revry', 
  'Runtime', 
  'Screambox', 
  'Screambox Amazon Channel', 
  'ScreenPix Apple TV Channel', 
  'Shahid VIP', 
  'ShortsTV Amazon Channel', 
  'Shout! Factory TV', 
  'Showtime', 
  'Showtime Amazon Channel', 
  'Showtime Apple TV Channel', 
  'Showtime Roku Premium Channel', 
  'Shudder', 
  'Shudder Amazon Channel', 
  'Shudder Apple TV Channel', 
  'Smithsonian Channel', 
  'Spamflix', 
  'Spectrum On Demand', 
  'Starz', 
  'Starz Amazon Channel', 
  'Starz Apple TV Channel', 
  'Starz Roku Premium Channel', 
  'Sun Nxt', 
  'Sundance Now', 
  'Takflix', 
  'TBS', 
  'TCM', 
  'The CW', 
  'The Roku Channel', 
  'TNT', 
  'Topic', 
  'Topic Apple TV Channel', 
  'Troma NOW', 
  'tru TV', 
  'True Story', 
  'Tubi TV', 
  'Univer Video', 
  'UP Faith & Family Apple TV Channel', 
  'Urban Movie Channel', 
  'USA Network', 
  'Viaplay', 
  'Viewster Amazon Channel', 
  'VIX ', 
  'Vudu', 
  'VUDU Free', 
  'WOW Presents Plus', 
  'WWE Network', 
  'Xumo Play', 
  'YouTube', 
  'YouTube Free', 
  'YouTube Premium', 
  'Yupp TV'
];